# Generated by Django 3.2.6 on 2021-08-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210830_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='who_is',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=100),
        ),
    ]
