# Generated by Django 3.2.6 on 2021-10-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newuser_who_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='admin_key',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
