# Generated by Django 3.2.6 on 2021-10-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211006_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='who_is',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
