# Generated by Django 3.2.6 on 2021-08-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('electronic', 'electronic'), ('computer', 'computer'), ('economic', 'economic')], default='choose your field', max_length=100)),
                ('topic', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('about_meeting', models.TextField(max_length=500)),
                ('zoom_url', models.URLField()),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
