# Generated by Django 3.2.6 on 2021-08-26 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_meetings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetings.meetings')),
                ('new_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
