# Generated by Django 3.2.6 on 2021-10-14 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='area',
        ),
        migrations.AddField(
            model_name='meetings',
            name='zoom_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MeetingsRequest',
        ),
    ]
